### PR TITLE
Improving speed of Comn.CountBits

### PR DESCRIPTION
**Pull request by FlameHorizon**
Finally, made it.

#200

### CODE REVIEW

**Comment by FlameHorizon** [comment]
I would like to also fix casing for every method which is in Comn class. And also, maybe change name of the class for Comn, to Common. What do you think about it?

**Comment by Tirlititi** [comment]
Can you revert the changes you made to the ``.csproj`` and ``.sln`` files?
I am not sure about ``Memoria.Tests``. You should ask Albeoris to know what's its purpose.
Ideally, it would be nice if you keep only the changes in ``Comn.cs``, thanks.

**Comment by Tirlititi** [comment]
But that is not its original purpose. It looks like some kind of dummied project to test things about reading/manipulating the event scripts. Besides, I am not for adding this kind of time-consuming tests.

**Comment by FlameHorizon** [comment]
Last commit has been reverted.

**Pull request merged**
