### PR TITLE
Enable Custom Shader For Field & Battle Character

### PR DESCRIPTION
**Pull request by EricHu33**
# What This PR Add To The Project
The PR provide **optional shaders** for **character on field map** and **characters(include enemy) in battle.**
With 2 type of shading style to chooese from - **Toon & Realism.**
Addditionaly user can choose whether to enable a **Outline** effect for each character.
BattleComparison

## Implementation
Below demonstrate my implement steps for writing the shader.
ShaderFlow
## Optional shader files added in this PR are list below :
 
For battle characters
 - Memoria.Patcher/StreamingAssets/Shaders/PSX/BattleMap_StatusEffect_RealLighting.txt
 - Memoria.Patcher/StreamingAssets/Shaders/PSX/BattleMap_StatusEffect_Toon.txt

For create ambient ligh
ting runtime in battle
 - Memoria.Patcher/StreamingAssets/Shaders/PSX/Skybox_Cubemap.txt
 
For fieldmap characters
 - Memoria.Patcher/StreamingAssets/Shaders/PSX/FieldMapActorShadow.txt
 - Memoria.Patcher/StreamingAssets/Shaders/PSX/FieldMapActor_RealLighting.txt
 
 # Changes on the scripts
 
 ## Shader swap
 Instead of using original shader, we check whether the user has choose to enable custom shader or not.
 If so, [we will use the optional shader text file](https://github.com/Albeoris/Memoria/pull/531/files#diff-727ade92b8106301a16ae8954639ad777c32c609f3ecf5b489a622185d5d62f9R32).
 ```
 // Original code example
this.battleShader = ShadersLoader.Find("PSX/BattleMap_StatusEffect");
// Change in this PR
this.battleShader = ShadersLoader.Find(ShadersLoader.GetCurrentBattleCharcterShader);

...
...
...
// shader file to choose from : 
private const string DefaultBattleCharacterShader = "PSX/BattleMap_StatusEffect";
private const string ToonBattleCharacterShader = "PSX/BattleMap_StatusEffect_Toon";
private const string RealismBattleCharacterShader = "PSX/BattleMap_StatusEffect_RealLighting";

private const string DefaultFieldCharacterShader = "PSX/FieldMapActor";
private const string ToonFieldCharacterShader = "PSX/FieldMapActor_Toon";
private const string RealismFieldCharacterShader = "PSX/FieldMapActor_RealLighting";
 ```
 
 
## Smooth Mesh Noraml
There's some extra logic on C# script side besides swap shader. Mainly for smooth mesh normal.
See [Normal Solver](https://github.com/Albeoris/Memoria/pull/531/files#diff-48a69e5df3bad9134bf4844673c0573dd5d4327c5e006523282b7065f9bbf6c6)

The reason to smooth mesh normal is to have good looking shading effect on the low-poly character of FF9.
Below comparison image shows the difference between shading with/wihout smoothed normal mesh .
Without SmoothNormal With SmoothNormal

## Ambient Lighting
Ambient lighting in games refers to a type of light that uniformly illuminates all surfaces in the game environment, regardless of their location or orientation. It is used to simulate the effect of indirect light that has been scattered and diffused by the environment. It helps to soften shadows and make scenes look more natural by providing a base level of illumination, preventing completely dark areas in the game.
With SmoothNormalWith SmoothNormal
To achieve this I cheat by create a[ reflection probe](https://docs.unity3d.com/Manual/class-ReflectionProbe.html) at runtime. Using the reflection probe we capture the battle map's 3D scene into a texture therefor use it as a based for ambient lighting.

By calling [DynamicGI.UpdateEnvironment();](https://github.com/Albeoris/Memoria/pull/531/files#diff-d6859bb928dc0ff2f40d033a560e7484a23529316b1a56376ad467b128bcb5e5R702). Unity can transform the capture skybox into a data format that shader read for lighting info(Spherical Harmonics). This operation takes only 1~2 frame in the whole battle. So should be fine regardless performance impact.

# Current Launcher UI

image

### CODE REVIEW

**Comment by SamsamTS** [comment]
Since last we spoke on discord Tirlititi made sure shaders can be modded so I'm not sure this PR is need anymore. You can simply do a mod. Personally I'm fine with integrating your shaders into memoria but it might be easier for you to maintain if it's a mod,

You can create a folder named <YourMod> and put your custom shaders in <YourMod>\StreamingAssets\Shaders\PSX\ and they should be loaded when <YourMod> is enabled in the mod manager.
You will also need to provide a mod description file: https://github.com/Albeoris/Memoria/wiki/Mod-Manager#mod-description

**Comment by EricHu33** [comment]
> Since last we spoke on discord @Tirlititi made sure shaders can be modded so I'm not sure this PR is need anymore. You can simply do a mod. Personally I'm fine with integrating your shaders into memoria but it might be easier for you to maintain if it's a mod,
> 
> You can create a folder named and put your custom shaders in \StreamingAssets\Shaders\PSX\ and they should be loaded when is enabled in the mod manager. You will also need to provide a mod description file: https://github.com/Albeoris/Memoria/wiki/Mod-Manager#mod-description

I see, one more question, can i have custom C# script in my mod?
Like adding some custom logic inside the battle camera script, modify shader loading path ..etc

**Comment by snouz** [comment]
I'm personally not against integrating it as a feature behind a setting, and it even makes modding easier:
- you keep a default vanilla look, and default shaded look
- anyone can make a mod that changes the shaded look
- even if you mod it, you keep a choice between vanilla and shaded.

**Comment by EricHu33** [comment]
Yes, I'm not intend to rush the merge. More like open a discussion about how these kind of feature can be integrated to the community. For example
maybe a list if toggle to choose which shader to load is better.

- battle character
  - use realistc shader
  - use toon shader
  - use original
- field character
 - use toon-outline shader
 - use toon shader
 - use original 
- image effect
 - use filter A
 - use color grading A
 - use original
 
> Modifying the shader loading path in the C# code is OK. Just make sure that there should always be the possibility to play with the vanilla settings, except when it concerns bug fixes.
> 
> However, you'll have a hard time (that's an understatement) doing anything at all with the battle camera. The camera movements are computed by the SFX engine in the external DLL `FF9SpecialEffectPlugin.dll` and in combination with the SFX itself. If you use another camera movement, the SFX will not render correctly.

I'll not touch the camera movement logic. but only inject some code inside the OnRenderImage callback of the BattleMapCameraController to render some image (in screen space). effect such as filter and SSAO will required it.

**Comment by SamsamTS** [comment]
Here what I propose for the options. We make a new section in Memoria.ini called Shader (or CustomShader):

```
[Shader]
    ;BattleCharacter (default RealLight) Must be either None, RealLight, Toon
    ;FieldCharacter (default RealLight) Must be either None, RealLight, Toon, ToonOutline
    ;FieldCharacter (default RealLight) Must be either None, FilterA, etc..
Enabled = 1 ;Enable/disable custom shader
BattleCharacter = RealLight
FieldCharacter = RealLight
PostProcessing = None

```

**Comment by barkermn01** [comment]
> 342686537-c47af116-6d09-46a6-9831-1dbf004acdda

Thinking perhaps this should be a drop down pick the style that way in the future Mods could add this support since real time C# Assembly loading is possible, and should we get to that stage it allows mod creators to just create there own and it be added to the drop down. (just thinking future proofing, and usability check boxes like this could be confusing)

**Comment by snouz** [comment]
Hi @barkermn01, we discussed it on discord with Eric earlier today.

Eric is busy this week but will try to cleanup the commit for next version
I offered to add a return button from the second menu, and make that page the "advanced" or "experimental" menu, with a more discreet button.
I also suggested this
image

I also think the options should be:

- Field shading: 0 = none, 1 = toon, 2 = realistic
- Battle shading: 0 = none, 1 = toon, 2 = realistic
- Outline field
- Outline battle

As there are some mutually exclusive values.

**Comment by EricHu33** [comment]
Hello, the PR is clean up and ready to review. 
I've rewrote the whole PR description as well.

**Comment by shinra358** [comment]
So I've done a little tinkering and i've activated transparency on chars and enemies in battle. how do i add it to have it play all the time without the launcher? currently i can only pose it as one of the shaders already available in the launcher but I can't make it activate without choosing the shader launcher options.

**Pull request merged**
