### PR TITLE
Analog movement + Skip Intros

### PR DESCRIPTION
**Pull request by kellymoen**
Couple of mods I've done to enable true analogue movement as in the PSX version and to skip intro splash screens.

### CODE REVIEW

**Comment by Albeoris** [comment]
Thank you. If there are new ideas - welcome. :)

**Comment by Albeoris** [comment]
@kellymoen hi!

Can you say what the hell is going on?
```
	public String SpecificPlatformHorizontalInputKey
	{
		get
		{
			if (Application.platform == RuntimePlatform.Android)
			{
				return "Horizontal Android";
			}
			if (Application.platform == RuntimePlatform.IPhonePlayer)
			{
				return "Horizontal iOS";
			}
			return "Horizontal NonMobile"; // We are here
		}
	}
```

"Horizontal" will return valid value but "Horizontal NonMobile" returns some crap around -0.085
I will try to remove it but not sure it's not broke XBOX360 gamepad.

**Comment by kellymoen** [comment]
Haha the input management system and character controller for this port was clearly hacked together with no analysis or design. This is probably what causes the "moving left bug". It can be removed and the controller still works fine. e.g

`    public Single GetHorizontalNavigation()
    {
        return UnityXInput.Input.GetAxis(this.DefaultHorizontalInputKey);
    }`

**Comment by Albeoris** [comment]
I think the same.
Thank you, I'll do it.

**Pull request merged**
