### PR TITLE
Complete redesign of the launcher and mod manager

### PR DESCRIPTION
**Pull request by snouz**
### AFTER
2024-01-16 23_39_53-Final Fantasy IX Launcher
2024-01-17 01_41_42-Configuration des Mods - janvier 2024

--------
### BEFORE
2024-01-16 22_13_54-Final Fantasy IX Launcher
image

### CODE REVIEW

**Comment by WarpedEdge** [comment]
Looks amazing!

**Comment by snouz** [comment]
Thanks!
image

**Comment by snouz** [comment]
image

**Comment by DV666** [comment]
Wow, nice ! Congrats !

**Pull request merged**
