### PR TITLE
[WIP] FPS independent gameplay(30 fps, 60 fps, 120 fps, etc. on battles/fields/overworld)

### PR DESCRIPTION
**Pull request by Iamgoofball**
absolutely not ready, just making sure it's up on the git, ~~still currently unplayable due to issue with battles not actually running player commands~~(this was user error on my part, it works just fine) and battles are running faster speed-wise than intended based on PSX footage

### CODE REVIEW

**Comment by Tirlititi** [comment]
Thanks a bunch for letting me take over that work and for the insightful discussions

**Comment by faospark** [comment]
is this already tweakable in the latest release ?

**Comment by Iamgoofball** [comment]
Tirlititi was able to do a much better implementation on the Main branch, check it out there

**Comment by faospark** [comment]
gocha . sorta my bad cause i had check updates in launcher not realizing that it reverts memoria to an older version

**Pull request closed without merging**
